apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-tcp-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-tcp-proxy
  template:
    metadata:
      labels:
        app: postgres-tcp-proxy
    spec:
      containers:
        - name: nginx
          image: nginx
          command:
            - /bin/sh
            - -c
            - "until nslookup postgres.my-namespace.svc.cluster.local; do sleep 2; done && nginx -g 'daemon off;'"
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: postgres-nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-nginx-config
data:
  nginx.conf: |
    events {}
    stream {
        server {
            listen 5432;
            resolver kube-dns.kube-system.svc.cluster.local;
            proxy_pass postgres.default.svc.cluster.local:5432;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-proxy
spec:
  selector:
    app: postgres-tcp-proxy
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP