name: Docker Image CI

env:
  APP_NAME: setrr
  REPOSITORY_NAME: denislabelle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin' # or any other distribution you prefer
          java-package: jdk
          # check-latest: false
          # server-id: github
          # server-username: ${{ secrets.GITHUB_ACTOR }}
          # server-password: ${{ secrets.GITHUB_TOKEN }}
          # overwrite-settings: true

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Capture version name
        id: capture_version
        run: |
          VERSION_NAME=$(./gradlew printVersionName -q)
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - name: Use version name
        run: echo "The version name is ${{ env.VERSION_NAME }}"
        
      - name: Build & Tag the Docker image for ${{ env.REPOSITORY_NAME }}/${{ env.APP_NAME }}:${{ env.VERSION_NAME }}
        run: docker build . --file Dockerfile --tag ${{ env.REPOSITORY_NAME }}/${{ env.APP_NAME }}:${{ env.VERSION_NAME }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image # ${{ env.REPOSITORY_NAME }}/${{ env.$APP_NAME }}:${{ env.VERSION_NAME }}
        run: docker push ${{ env.REPOSITORY_NAME }}/${{ env.APP_NAME }}:${{ env.VERSION_NAME }}
