name: Build, Deploy, Apply to do-tor1-faith-no-more-v1

env:
  APP_NAME: setrr
  REPOSITORY_NAME: denislabelle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin' # or any other distribution you prefer
          java-package: jdk
          
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Capture version name
        id: capture_version
        run: |
          VERSION_NAME=$(./gradlew printVersionName -q)
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - name: Use version name
        run: echo "The version name is ${{ env.VERSION_NAME }}"
        
      - name: Build & Tag the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.REPOSITORY_NAME }}/${{ env.APP_NAME }}:${{ env.VERSION_NAME }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image 
        run: docker push ${{ env.REPOSITORY_NAME }}/${{ env.APP_NAME }}:${{ env.VERSION_NAME }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
                 
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'  # You can specify a specific version if needed
        
      # - name: Configure Kubernetes credentials
      #   run: |
      #     echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
      #     export KUBECONFIG=kubeconfig.yaml
      #     mkdir $HOME/.kube
      #     cp kubeconfig.yaml $HOME/.kube/config
          
        
      - name: Set Kubernetes context
        run: |
          mkdir $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      - name: Apply Kubernetes deployment
        run: |
           kubectl config use-context do-tor1-faith-no-more-v1  
           kubectl apply -f ${{ github.workspace }}/k8s/deployment.yaml --validate=false
