name: Docker Image CI

env:
  APP_NAME: setrr
  REPOSITORY_NAME: denislabelle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Capture version name
        id: capture_version
        run: |
          VERSION_NAME=$(./gradlew printVersionName -q)
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - name: Use version name
        run: echo "The version name is ${{ env.VERSION_NAME }}"
        
      - name: Build & Tag the Docker image for $REPOSITORY_NAME/$APP_NAME:${{ env.VERSION_NAME }}
        run: docker build . --file Dockerfile --tag $REPOSITORY_NAME/$APP_NAME:${{ env.VERSION_NAME }}

      - name: Push Docker Image # $REPOSITORY_NAME/$APP_NAME:${{env.version_name}}
        run: docker push --tag $REPOSITORY_NAME/$APP_NAME:${{ env.VERSION_NAME }}
