name: Docker Image CI

env:
  APP_NAME: setrr
  REPOSITORY_NAME: denislabelle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Retrieve Version
      run: |
       echo "::setOutput name=VERSION_NAME::$(${{github.workspace}}/gradlew -q printVersionName)"
      id: build_version

    - name: Get version
      run: | 
        echo "version_name=${{steps.build_version.outputs.VERSION_NAME}}" >> $GITHUB_ENV
    
    - name: Build & Tag the Docker image
      run: docker build . --file Dockerfile --tag $REPOSITORY_NAME/$APP_NAME:${{env.version_name}}

    - name: Push Docker $REPOSITORY_NAME/$APP_NAME:${{env.version_name}}
      run: docker push --tag $REPOSITORY_NAME/$APP_NAME:${{env.version_name}}
